services:
  smo:
    container_name: smo
    build: .
    ports:
      - 5000:5000
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
    - .db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s