services:
  smo:
    container_name: smo
    build: .
    volumes:
      - type: bind
        source: ~/.kube/
        target: /home/python/.kube
        read_only: true
      - type: bind
        source: ~/.docker/
        target: /home/python/.docker
        read_only: true
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    extra_hosts:
    - "host.docker.internal:host-gateway"
  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
    - .db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 3s
