services:
  smo:
    container_name: smo
    build: .
    volumes:
      - type: bind
        source: ~/.kube/
        target: /kube
        read_only: true
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    network_mode: host
  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
    - .db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 3s
    network_mode: host
